TC_08_33_01 | Edit form
TheFocusTech/SignaturelyQA pull request #142
Opened 2024-06-27 21:31 UTC by mlimau

- to Fixture Create Form 'clickInitialFieldItem' method was added acc to Requirements and since tests were flaky
- locator 'optionsDropdown' was added to t'ableComponent', since in the test 'optionsBtn' does not work, and  'optionsDropdown' locator does not work with some tests, so we need both

2024-06-27 22:45 UTC, IrynaKolh requested changes

2024-06-28 00:46 UTC, mlimau commented on new_pom/components/tableComponent.js
> +        this.optionsDropdown = this.page.locator('.documents__optionsDropdownTrigger').filter({ hasText: 'Options' }).first();
fixed

2024-06-28 00:55 UTC, IrynaKolh approved these changes

2024-06-28 05:17 UTC, teya-teya commented on new_pom/modalWindows/prepareForSignatureModal.js
> +            await this.signOnFieldsMenu.waitFor();
Я не знаю куда пропало, но когда я делала свой тест в аллюре я этот метод добавляла в аплюр. А тут почему то нет

2024-06-28 05:42 UTC, teya-teya commented on new_pom/components/tableComponent.js
> +        await step('Click on "Edit" dropdownItem', async () => {
Мне кажется лучше назвать Click on the "Edit" item from the dropdown.

2024-06-28 05:50 UTC, teya-teya commented on new_pom/pages/forms/updateFormPage.js
> +        this.deleteDocumentBtn = this.page.locator('.documentPreview__document-header-button-icon');
мне кажется можно сделать локатор более понятным обратившись чуть выше
![image](https://github.com/TheFocusTech/SignaturelyQA/assets/142177100/15838847-97cf-4b00-a7ec-9f37b6e4c581)
как я писала в другом ПР можно попробовать так 
getByRole('button').locator('button cancel') или например по тегу locatotor('button cancel')

2024-06-28 06:31 UTC, verafes commented on new_pom/pages/forms/updateFormPage.js
> +        this.deleteDocumentBtn = this.page.locator('.documentPreview__document-header-button-icon');
locator('button cancel') не будет работать, т.к перед каждым классом нужно ставить точку -> '.button.cancel'

2024-06-28 06:39 UTC, verafes commented on tests/03CreateDocument.spec.js
> +		await signPage.uploadFileTab.clickPrepareDocumentBtn();
В VS code все правильно выравнено: test на 4 пробела от describe, и шаги на 4 пробела от test. Ранее меньше было.

2024-06-28 06:42 UTC, teya-teya commented on new_pom/pages/forms/updateFormPage.js
> +        this.deleteDocumentBtn = this.page.locator('.documentPreview__document-header-button-icon');
точно, Спасибо Вера!

2024-06-28 08:13 UTC, teya-teya commented on new_pom/pages/forms/updateFormPage.js
> +        this.fillTemplateBtn = this.page.getByRole('button', { name: 'Fill Template' });
и еще насколько я поняла общие элементы со страницей create необходимо разместить в компонентах и подтягивать уже их на страницы create и update

2024-06-28 13:42 UTC, mlimau commented on new_pom/components/tableComponent.js
> +        this.firstFormTitle = this.page.locator('.table__column.table__column--text').nth(1);
this.firstFormTitle = this.page.getByText('Edited Form Name'); - можно ,так работает, поправила

2024-06-28 13:45 UTC, mlimau commented on tests/08Forms.spec.js
> +        })
здесь появляются два toast messages,  и по requirements я должна их проверить

2024-06-28 13:48 UTC, mlimau commented on tests/03CreateDocument.spec.js
> +		await signPage.uploadFileTab.clickPrepareDocumentBtn();
не пойму, вроде в spec всё так:: 
<img width="802" alt="image" src="https://github.com/TheFocusTech/SignaturelyQA/assets/129126676/a5fb33d1-1097-4e28-9157-6840d86a24e0">

2024-06-28 13:49 UTC, mlimau commented on tests/03CreateDocument.spec.js
> +		await signPage.uploadFileTab.clickPrepareDocumentBtn();
space 4 везде:
<img width="806" alt="image" src="https://github.com/TheFocusTech/SignaturelyQA/assets/129126676/4d2c472e-f9c3-4fd0-8d27-cf58ea7e2389">

2024-06-28 17:17 UTC, mlimau commented on tests/08Forms.spec.js
> +        await formsPage.table.clickOptionsBtn(0);
refactored

2024-06-28 19:34 UTC, mlimau commented on new_pom/pages/forms/updateFormPage.js
> +        this.fillTemplateBtn = this.page.getByRole('button', { name: 'Fill Template' });
Corrected, create component file for both pages

2024-06-28 23:38 UTC, teya-teya commented on helpers/preconditions.js
> +        //await createFormPage.createUpdateForm.fillFormNameField(SIGNERS_DATA.signerEmail1)
Строчки закомментированы

2024-06-28 23:43 UTC, teya-teya commented on new_pom/pages/forms/createFormPage.js
> +        this.createUpdate = new CreateUpdateFormComponent(this.page)
Может лучше все таки createUpdateForms

2024-06-28 23:45 UTC, teya-teya commented on new_pom/pages/forms/updateFormPage.js
> -import {step} from 'allure-js-commons';
Зачем удалять степ? Он же нужен тут

2024-06-28 23:51 UTC, teya-teya reviewed
Так в общем хорошо, но надо обновить ветку. Метод doCanvasClicks() был переименован в cluckDocumdntBody()
И если сейчас рефакторинг пройдет, то много изменений будет

2024-07-01 01:17 UTC, verafes commented on new_pom/components/createUpdateFormComponent.js
> +        await this.formNameField.fill(name);
строка кода метода должны быть сдвинута на 4 пробела вправо от аннотации степа

2024-07-01 01:17 UTC, verafes commented on new_pom/components/createUpdateFormComponent.js
> +        await this.optionalMessageField.fill(message);
строка кода метода должны быть сдвинута на 4 пробела вправо от аннотации степа

2024-07-01 01:17 UTC, verafes commented on new_pom/components/createUpdateFormComponent.js
> +        await this.fillTemplateBtn.click();
2 строкм кода метода должны быть сдвинуты на 4 пробела вправо от аннотации степа

2024-07-01 01:17 UTC, verafes commented on tests/08Forms.spec.js
> +            "https://docs.google.com/document/d/1Qce7tKWOwVYtPxgQv_8ae-HUkbAgeOFph0lB_eziY_k/edit#heading=h.c5mhxwvn5pxt",
Лучше оформить линки qase.io и google doc с переменными, по примеру как сделано в других тестах.

2024-07-01 01:17 UTC, verafes commented on tests/08Forms.spec.js
> +            'https://docs.google.com/document/d/1Qce7tKWOwVYtPxgQv_8ae-HUkbAgeOFph0lB_eziY_k/edit#heading=h.go4aj45aaddt',
Нужно оформить линки qase.io и google doc с переменными, по примеру как сделано в других тестах.

2024-07-01 21:33 UTC, closed without merging

2024-07-01 21:34 UTC, mlimau commented
new one is created since main brunch was updated