TC_05_19_02 | Verify that deleted documents have been moved to the trash by using checkboxes and Select_options dropdown menu and then deleted permanently
TheFocusTech/SignaturelyQA pull request #195
Opened 2024-07-02 14:40 UTC by nadya0101

add TC_05_19_02

2024-07-04 18:53 UTC, ArinaJur approved these changes
LGTM

2024-07-04 19:37 UTC, IrynaKolh requested changes

2024-07-04 19:37 UTC, IrynaKolh commented on new_pom/components/tableComponent.js
> +        this.documentTitleToSave = '';
Надя, на мой взгляд это не очень хорошая идея добавлять эти переменные в конструктор. Лучше создать методы, которые будут возвращать нужное вам значение.

2024-07-04 19:37 UTC, IrynaKolh commented on new_pom/pages/sign/signPage.js
> +
Можно не создавать отдельный метод, а просто в тесте использовать page.reload() поскольку это временный костыль, и когда уберут этот баг с приложения, будет проще убрать 1 строку в тесте.

2024-07-04 19:55 UTC, nadya0101 commented on new_pom/components/tableComponent.js
> +        this.documentTitleToSave = '';
Ира, не срабатывает так, мы провобали с Ириной

2024-07-04 19:58 UTC, nadya0101 commented on new_pom/pages/sign/signPage.js
> +
Ира, там при загрузке сразу трех документов, если не обновлять страницу, то все три документа записываются как один (система их объединяет в один файл, а не записывает как разные)

2024-07-04 23:39 UTC, IrynaKolh requested changes

2024-07-04 23:39 UTC, IrynaKolh commented on new_pom/components/tableComponent.js
> +        this.documentTitleToSave = '';
Все щас будет работать)

удалите эти 3 строчки:
        this.documentTitleToSave = '';
        this.documentsTitlesToDelete = [];
        this.documentsTitles = [];

2024-07-04 23:39 UTC, IrynaKolh commented on new_pom/components/tableComponent.js
> +    async getAllDocumentsTitles() {
замените свой метод на этот:

    async getAllDocumentsTitles() {
        await this.objectTitle.first().waitFor({ state: 'visible' });
        const documentsTitles = await this.objectTitle.allInnerTexts();
        return documentsTitles;
    }

2024-07-04 23:39 UTC, IrynaKolh commented on new_pom/components/tableComponent.js
>      async waitForTable(time) {
удалите этот метод полностью, плохо хардкодом делать паузу на n секунд

2024-07-04 23:39 UTC, IrynaKolh commented on new_pom/components/tableComponent.js
> +    async checkRandomDocuments() {
а этот метод должен выглядеть так:

    async checkRandomDocuments() {
        return await step('Check two random documents and collect their titles', async () => {
            const documentsTitles = await this.getAllDocumentsTitles();
            const randomIndex = getRandomIndex(documentsTitles);            
            let documentsTitlesToDelete = [];
            const documentTitleToSave = await this.objectTitle.nth(randomIndex).innerText();
            for (let i = 0; i < documentsTitles.length; i++) {
                if (i !== randomIndex) {
                    const titleToDelete = await this.objectTitle.nth(i).innerText();
                    documentsTitlesToDelete.push(titleToDelete);
                    await this.objectCheckbox.nth(i).click();                   
                }
            }
            return {
                documentsToDelete: documentsTitlesToDelete,
                documentToSave: documentTitleToSave,
            };
        });
    }

2024-07-04 23:39 UTC, IrynaKolh commented on new_pom/pages/sign/signPage.js
> +
пусть будет) я соглашусь с вами, что это для прекондишин хороший трюк

2024-07-04 23:39 UTC, IrynaKolh commented on tests/05DocumentsTyped.spec.js
> +        await documentsPage.table.checkRandomDocuments();
замените эту строку на 
const { documentsToDelete, documentToSave } = await documentsPage.table.checkRandomDocuments();

2 следующие удалите

2024-07-06 16:07 UTC, IrynaKolh approved these changes

2024-07-06 16:11 UTC, merged