Em/03 08 03
TheFocusTech/SignaturelyQA pull request #207
Opened 2024-07-03 20:38 UTC by Eduard-QA

2024-07-04 21:54 UTC, IrynaKolh requested changes

2024-07-04 21:54 UTC, IrynaKolh commented on helpers/preconditions.js
> +        await finalStepPage.toast.waitForToastIsHiddenByText(TOAST_MESSAGE.success);
на этом шаге нет finalStepPage
если хотите проверить toast то используйте prepareForSignatureModal.toast.waitForToastIsHiddenByText(TOAST_MESSAGE.success);

2024-07-04 21:54 UTC, IrynaKolh commented on new_pom/pages/sign/signPage.js
> +        this.chooseTemplateField = this.page.locator("p.uiSelect__select-placeholder");
Эдуар, подожди код Анастасии - это должен быть отдельный компонент

2024-07-04 21:54 UTC, IrynaKolh commented on new_pom/pages/sign/signPage.js
> +        this.chooseTemplateField = this.page.locator("p.uiSelect__select-placeholder");
можешь посмотреть е ее драфт ПР

2024-07-05 04:17 UTC, Eduard-QA commented on helpers/preconditions.js
> +        await finalStepPage.toast.waitForToastIsHiddenByText(TOAST_MESSAGE.success);
Запутался.. сначала там так и было, но тест падал в СI и указывал на эту строку как ошибка
перепроверил - показывало страницу finalStepPage ( не знаю как.. ) 
поменял - в CI ошибка перестала появляться
Вернул обратно, запустил - посмотрю 
Но на локальной ветке проходят оба варианта ... может вообще убрать ((

2024-07-05 04:18 UTC, Eduard-QA commented on new_pom/pages/sign/signPage.js
> +        this.chooseTemplateField = this.page.locator("p.uiSelect__select-placeholder");
ок

2024-07-05 23:31 UTC, Eduard-QA commented on new_pom/pages/sign/signPage.js
> +        this.chooseTemplateField = this.page.locator("p.uiSelect__select-placeholder");
> Эдуар, подожди код Анастасии - это должен быть отдельный компонент

Тест довел, проходит 
Когда код Анастасии войдет в main поменяю путь к локаторам

2024-07-07 15:59 UTC, IrynaKolh approved these changes

2024-07-07 16:04 UTC, OlgaPerepelitzki approved these changes

2024-07-07 16:07 UTC, merged