RF test TC_07_27_01 | Verify that user can create a template | to new…
TheFocusTech/SignaturelyQA pull request #76
Opened 2024-06-18 12:02 UTC by Katerina-Poliit

… POM

2024-06-18 16:03 UTC, IrynaKolh requested changes

2024-06-19 10:10 UTC, Katerina-Poliit commented on new_pom/modalWindows/prepareforSigningModal.js
> +export default class PrepareForSigningModal {
использовала

2024-06-19 10:11 UTC, Katerina-Poliit commented on tests/07.Templates.spec.js
> +   await signPage.sideMenuTemplates.clickCreateTemplate();
создать TemplatePage и добавить в base.js

2024-06-19 11:44 UTC, teya-teya commented on new_pom/components/createNewTemplateComponent.js
> +          await this.templateNameField.fill(CREATE_TEMPLATE.nameField);
мне кажется в сам метод надо вставлять что то вроде универсального name, а конкретные данные из testData подтягивать в сам тест а не метод
То есть сделать так:
async fillTemplateNameField(name) {
        try {
          await this.templateNameField.fill(name);
        } finally {

        }
      }

2024-06-19 11:44 UTC, teya-teya commented on new_pom/components/createNewTemplateComponent.js
> +          await this.optionalMessageField.fill(CREATE_TEMPLATE.optionalMessage);
тут тоже самое

2024-06-19 11:44 UTC, teya-teya commented on new_pom/components/createNewTemplateComponent.js
> +      async fillCreateTemplateRolesField() {
и тут

2024-06-19 11:44 UTC, teya-teya commented on new_pom/components/fileUploaderComponent.js
> +        await this.progressBar.waitFor('visible');
Не надо менять эти строки
        await this.progressBar.waitFor({ state: 'visible' });
        await this.progressBar.waitFor({ state: 'hidden' });
на эти
        await this.progressBar.waitFor('visible');
        await this.progressBar.waitFor('hidden');
 иначе ожидание не будет работать как надо

2024-06-19 11:44 UTC, teya-teya commented on new_pom/components/sideMenuComponent.js
>      async clickSettings() {
не совсем понимаю, тут происходит дублирование метода clickSettings()?

2024-06-19 11:44 UTC, teya-teya commented on new_pom/modalWindows/prepareForSignatureModal.js
> +    async performSignature(startX, startY) {
Я правильно понимаю что этот метод для выполнения клика по Canvas с целью создания подписи на ней?
Если да, то уже существует метод  называется doCanvasClicks() и выполняется после клика на  clickSignFieldsItem() если нужно поставить подпись

2024-06-19 11:44 UTC, teya-teya commented on new_pom/modalWindows/prepareForSignatureModal.js
> +        this.signBtn = this.page.getByRole('complementary').getByText('Sign');
для этого элемента уже существует локатор 
this.signFieldsItem = this.page.locator('li').getByText('Sign');
и метод для клика
    async clickSignFieldsItem() {
        await this.signFieldsItem.waitFor({ state: 'visible' });
        await this.signFieldsItem.click();
    }

2024-06-19 11:44 UTC, teya-teya commented on new_pom/pages/documents/templatesPage.js
> +
templatesPage.js  и templatesCreateTemplate.js должны лежать в своей папке templatesPage а не в папке documents

2024-06-19 11:44 UTC, teya-teya commented on new_pom/pages/documents/templatesCreateTemplate.js
> +        this.formNewTemplate = new CreateNewTemplateComponent(this.page);
this.formNewTemplate = new CreateNewTemplateComponent(this.page); 
у вас в двух файлах.
так как этот элемент относится к странице templatesCreateTemplate.js то надо удалить его из templatesPage.js

2024-06-19 11:44 UTC, teya-teya commented on new_pom/pages/documents/templatesPage.js
> +        this.formNewTemplate = new CreateNewTemplateComponent(this.page);
здесь надо использовать не this.formNewTemplate = new CreateNewTemplateComponent(this.page);
а this.createNewTemplate = new CreateNewTemplatePage(this.page);
или что то похожее

2024-06-19 11:44 UTC, teya-teya commented on new_pom/pages/documents/templatesCreateTemplate.js
> +        this.formNewTemplate = new CreateNewTemplateComponent(this.page);
и этот файл должен быть назван createTemplateOnTemplatesPage.js или createTemplatePage.js

2024-06-19 11:47 UTC, teya-teya commented on tests/07.Templates.spec.js
> +import { expect } from "@playwright/test";
название фалов с тестами идет без точки то есть должно быть
07Templates.spec.js

2024-06-19 12:52 UTC, Katerina-Poliit commented on new_pom/pages/documents/templatesCreateTemplate.js
> +        this.formNewTemplate = new CreateNewTemplateComponent(this.page);
"так как этот элемент относится к странице templatesCreateTemplate.js то надо удалить его из templatesPage.js" в таком случает тест не работает

2024-06-19 12:52 UTC, Katerina-Poliit commented on new_pom/pages/documents/templatesPage.js
> +        this.formNewTemplate = new CreateNewTemplateComponent(this.page);
исправила

2024-06-19 13:05 UTC, Katerina-Poliit commented on new_pom/pages/documents/templatesPage.js
> +
исправила

2024-06-19 13:15 UTC, Katerina-Poliit commented on new_pom/modalWindows/prepareForSignatureModal.js
> +        this.signBtn = this.page.getByRole('complementary').getByText('Sign');
удалила и использовала уже существующий локатор

2024-06-19 13:23 UTC, Katerina-Poliit commented on new_pom/modalWindows/prepareForSignatureModal.js
> +    async performSignature(startX, startY) {
использовала doCanvasClicks()

2024-06-19 13:25 UTC, Katerina-Poliit commented on new_pom/components/sideMenuComponent.js
>      async clickSettings() {
это не мой, при подтягивании main продублировалось, убрала

2024-06-19 13:32 UTC, Katerina-Poliit commented on new_pom/components/fileUploaderComponent.js
> +        await this.progressBar.waitFor('visible');
)))вообще не поняла как я это сделала🧐

2024-06-19 13:57 UTC, Katerina-Poliit commented on new_pom/components/createNewTemplateComponent.js
> +          await this.templateNameField.fill(CREATE_TEMPLATE.nameField);
исправила

2024-06-19 13:57 UTC, Katerina-Poliit commented on new_pom/components/createNewTemplateComponent.js
> +          await this.optionalMessageField.fill(CREATE_TEMPLATE.optionalMessage);
исправила

2024-06-19 13:58 UTC, Katerina-Poliit commented on new_pom/components/createNewTemplateComponent.js
> +      async fillCreateTemplateRolesField() {
исправила

2024-06-19 16:47 UTC, teya-teya commented on new_pom/modalWindows/prepareForSignatureModal.js
> +    async clickcreateBtn() {
clickcreateBtn() не соблюден camaleCase

2024-06-19 16:50 UTC, teya-teya commented on new_pom/pages/templates/templatesCreateTemplate.js
> +import SideMenuComponent from "../../components/sideMenuComponent";
знаю что рекомендовала это название но я бы еще подумала на ним. 
в конце должно быть Page чтобы мы понимали что это именно Page
может оставить просто сreateTemplatePage.js

2024-06-19 16:55 UTC, teya-teya commented on new_pom/pages/templates/templatesPage.js
> +        this.createNewTemplate = new CreateNewTemplateComponent(this.page);
Смотрите у вас должна быть такая цепочка
templatesPage.js < createTemplatePage.js < createNewTemplateComponent.js
и в строчке теста так будет
вы компоненты подтягиваете через createTemplatePage а не напрямую в templatesPage
поэтому здесь должна быть такая строчка
this.createTemplate = new CreateTemplatePage(this.page);
названия файлов примерные

2024-06-19 16:56 UTC, teya-teya commented on new_pom/modalWindows/prepareForSignatureModal.js
> +    async clickbackToTempatesBtn() {
clickbackToTempatesBtn() не соблюден camaleCase

2024-06-19 16:58 UTC, teya-teya commented on new_pom/components/createNewTemplateComponent.js
> +      async clickfillTemlateBtn() {
clickfillTemlateBtn() не соблюден camaleCase

2024-06-19 17:13 UTC, verafes commented on fixtures/base.js
> +
Эти пустые строки 24-26 важны? если нет, то лучше убрать.

2024-06-19 18:52 UTC, SvetlanaKanel commented on new_pom/pages/templates/templatesPage.js
> +        this.createNewTemplate = new CreateNewTemplateComponent(this.page);
Не совсем увидела, куда кроме этой страницы мы будем подтягивать createTemplateComponent? Если он больше нигде не используется, то все можно прописать в саму page

2024-06-19 20:30 UTC, teya-teya commented on new_pom/pages/templates/templatesPage.js
> +        this.createNewTemplate = new CreateNewTemplateComponent(this.page);
согласна, если больше нигде не переиспользуется сreateNewTemplateComponent.js можно его локаторы и методы разместить сразу в CreateTemplatePage

2024-06-19 20:48 UTC, teya-teya reviewed
Катерина хотела так же обратить внимание, что у вас во многих файлах есть пустые не нужные строки.

2024-06-20 05:17 UTC, Katerina-Poliit commented on new_pom/components/sideMenuComponent.js
> +        this.settings = this.page.locator('.sidebar__wrapper').getByText('Settings');
getByRole('link', { name: 'Settings', exact: true })  не моё

2024-06-20 05:39 UTC, Katerina-Poliit commented on new_pom/modalWindows/prepareForSignatureModal.js
> +    async clickbackToTempatesBtn() {
это не мой метод

2024-06-20 05:42 UTC, Katerina-Poliit commented on fixtures/base.js
> +
убрала

2024-06-20 05:44 UTC, Katerina-Poliit commented on new_pom/components/createNewTemplateComponent.js
> +      async clickfillTemlateBtn() {
исправила

2024-06-20 05:52 UTC, Katerina-Poliit commented on new_pom/pages/templates/templatesCreateTemplate.js
> +import SideMenuComponent from "../../components/sideMenuComponent";
изменила

2024-06-20 06:34 UTC, teya-teya commented on new_pom/pages/templates/templatesPage.js
>  export default class NewTemplatesPage {
почему у вас класс называется NewTemplatesPage если это просто TemplatesPage

2024-06-20 06:34 UTC, teya-teya commented on new_pom/pages/templates/templatesPage.js
> +        this.createNewTemplate = new NewCreateTemplatePage(this.page);
Катерина вы пишете   this.createNewTemplate  но файл называете new NewCreateTemplatePage(this.page);

Думаю лучше new CreateNewTemplatePage(this.page);

простите, что так мучаю вас с этим названием

2024-06-20 06:35 UTC, Katerina-Poliit commented on new_pom/pages/templates/templatesPage.js
> +        this.createNewTemplate = new CreateNewTemplateComponent(this.page);
разместила  в CreateTemplatePage локаторы и методы

2024-06-20 06:43 UTC, Katerina-Poliit commented on new_pom/pages/templates/templatesPage.js
> +        this.createNewTemplate = new NewCreateTemplatePage(this.page);
исправила

2024-06-20 06:43 UTC, Katerina-Poliit commented on new_pom/pages/templates/templatesPage.js
>  export default class NewTemplatesPage {
исправила

2024-06-20 07:59 UTC, teya-teya commented on new_pom/pages/templates/createTemplatePage.js
> +export default class CreateNewTemplatePage {
Катерина, простите меня пожалуйста!
с этим New  я ошиблась вчера.
Это же вы использовали для обозначения того что класс создан в new_pom я только на смысл названия смотрела поэтому упустила этот момент.
В данном случае вы правильно вначале поставили его в начале NewCreateTemplatePage

просто при подтягивании на другой TemplatesPage тоже использовали new this.createNewTemplate, поэтому и сбило с мыслей.

По сути нет смысла называть переменную createNewTemplate, потому что когда вы что то создаете оно всегда новое.

В общем думаю класс надо назвать NewCreateTemplatePage, как у вас и было, сам файл останется с названием сreateTemplatePage.js
а в TemplatesPage использовать this.createTemplate = new NewCreateTemplatePage(this.page);

Еще раз простите мне мою невнимательность!

И заметила что снова появились пустые строки в некоторых файлах.

2024-06-20 08:32 UTC, Katerina-Poliit commented on new_pom/pages/templates/createTemplatePage.js
> +export default class CreateNewTemplatePage {
поправила)

2024-06-20 08:33 UTC, teya-teya approved these changes

2024-06-20 08:42 UTC, teya-teya commented on new_pom/pages/templates/createTemplatePage.js
> +export default class CreateNewTemplatePage {
Поздравляю)
Теперь надо чтобы IrynaKolh посмотрела, без нее апрува не выйдет

2024-06-20 08:55 UTC, Katerina-Poliit commented on new_pom/pages/templates/createTemplatePage.js
> +export default class CreateNewTemplatePage {
@IrynaKolh посмотрите PR, плиз)

2024-06-20 11:29 UTC, teya-teya commented on new_pom/pages/templates/createTemplatePage.js
> +        this.templateNameField = this.page.locator('.form__input').first();
Катерина, начала проходить по вашим шагам и обнаружила, что здесь можно нативный локатор использовать
.getByPlaceholder(/^A template name*/)

и для поля сообщения тоже.
page.getByPlaceholder(/^Add an optional message*/)
  и для роли
  page.getByPlaceholder('Role')

2024-06-20 11:33 UTC, teya-teya commented on tests/07Templates.spec.js
> +   await signPage.uploadFile.fileUploader.uploadFile('testDocuments/CSV.csv');
вот здесь тоже проглядела 
вы не через signPage должны обращаться к компоненту а импортировать его на страницу createTemplatePage

2024-06-20 12:00 UTC, Katerina-Poliit commented on new_pom/pages/templates/createTemplatePage.js
> +        this.templateNameField = this.page.locator('.form__input').first();
исправила

2024-06-20 12:08 UTC, teya-teya commented on tests/07Templates.spec.js
> +   const fileUploader = new FileUploaderComponent(templatePage.page);
Катерина вы видимо меня не так поняли компонент импортируется на страницу и прописывается в конструктор
Посмотрите как это сделано на signPage и UploadFileOnSignPage
и как я ранее писала в тесте он будет использоваться с помощью строчки
await templatesPage.createTemplate.fileUploader.uploadFile('testDocuments/CSV.csv');

то есть в строке
await signPage.uploadFile.fileUploader.uploadFile('testDocuments/CSV.csv') вы меняете часть signPage.uploadFile. на templatesPage.createTemplate.

2024-06-20 13:40 UTC, teya-teya commented on new_pom/pages/templates/templatesPage.js
> +        this.uploadFile = new UploadFileOnSignPage(this.page);
эта строчка лишняя, тк UploadFileOnSignPage(this.page) - это страница на signPage
а так все вроде правильно перенесли.

2024-06-20 13:41 UTC, teya-teya commented on tests/07Templates.spec.js
> +
похоже у вас expect пропал

2024-06-20 15:06 UTC, Katerina-Poliit commented on tests/07Templates.spec.js
> +   await prepareForSignatureModal.clickcreateBtn();
исправила)

2024-06-20 15:06 UTC, Katerina-Poliit commented on tests/07Templates.spec.js
> +
нашла )

2024-06-20 16:01 UTC, teya-teya commented on tests/07Templates.spec.js
> +
только обратите внимание что это статусы документов, надо или переменную переименовать и тогда отрефаторить тесты где она используется или создать новую для хранения статусов шаблонов

2024-06-20 18:26 UTC, teya-teya approved these changes
LGTM

2024-06-21 07:47 UTC, teya-teya commented
Катерина обратите внимание, что после решения конфликтов у вас строчки переместились туда где не должны  в base.js
Переместите их под импорты
![image](https://github.com/TheFocusTech/SignaturelyQA/assets/142177100/fcd3195b-1064-4bf6-b791-d4d91435ea43)

2024-06-21 08:09 UTC, teya-teya commented on fixtures/base.js
>  import NewSettingsAPIPage from "../new_pom/pages/settings/settingsAPIPage";
вижу что добавили, но при этом потеряли импорт своего класса TemplatesPage

2024-06-21 08:35 UTC, Katerina-Poliit commented on fixtures/base.js
>  import NewSettingsAPIPage from "../new_pom/pages/settings/settingsAPIPage";
поправила)

2024-06-21 08:46 UTC, teya-teya commented on fixtures/base.js
>  import NewSettingsAPIPage from "../new_pom/pages/settings/settingsAPIPage";
супер) видите теперь и тест прошел. Надо только Ирину К, а то никак не смерджим)

2024-06-21 08:59 UTC, Katerina-Poliit commented on fixtures/base.js
>  import NewSettingsAPIPage from "../new_pom/pages/settings/settingsAPIPage";
может её тегнуть в канале?

2024-06-21 11:39 UTC, IrynaKolh commented on new_pom/pages/templates/createTemplatePage.js
> +        this.fileUploader = new FileUploaderComponent(this.page);
Перенесите эту переменную до локаторов

2024-06-21 11:39 UTC, IrynaKolh commented on new_pom/modalWindows/prepareForSignatureModal.js
> +        try {
А зачем вам конструкция try?

2024-06-21 11:39 UTC, IrynaKolh commented on new_pom/modalWindows/prepareForSignatureModal.js
> +         this.signatureElement = this.page.locator('.documentPage .react-pdf__Page__canvas').last();
А локатор canvas вам не подходит разве?

2024-06-21 11:42 UTC, IrynaKolh approved these changes

2024-06-21 11:43 UTC, Katerina-Poliit commented on new_pom/pages/templates/createTemplatePage.js
> +        this.fileUploader = new FileUploaderComponent(this.page);
перенесла

2024-06-21 11:44 UTC, Katerina-Poliit commented on new_pom/modalWindows/prepareForSignatureModal.js
> +        try {
без неё у меня не сработало(, попробую ещё раз без неё

2024-06-21 11:51 UTC, Katerina-Poliit commented on new_pom/modalWindows/prepareForSignatureModal.js
> +         this.signatureElement = this.page.locator('.documentPage .react-pdf__Page__canvas').last();
мне посоветовали выше использовать  doCanvasClicks()

2024-06-21 12:04 UTC, IrynaKolh commented on new_pom/modalWindows/prepareForSignatureModal.js
> +         this.signatureElement = this.page.locator('.documentPage .react-pdf__Page__canvas').last();
Да, а потом этот метод. Просто выберете приблизительно один и тот же элемент.

2024-06-21 13:36 UTC, merged