TC_03_07_04 | Verify document is completed
TheFocusTech/SignaturelyQA pull request #89
Opened 2024-06-21 03:09 UTC by SvetlanaKanel

1. Add TC_03_07_04
2. optionsBtn --> optionsDropdown
3. clickOptionsBtn --> clickOptionsDropdown

2024-06-21 04:23 UTC, verafes approved these changes

2024-06-21 05:38 UTC, MariaKM approved these changes

2024-06-21 07:52 UTC, teya-teya commented on page_objects/documentsPage.js
> +        getoptionsDropdown: () => this.page.locator('.documents__optionsDropdown').first(),
Светлана не соблюден camelCase

2024-06-21 07:57 UTC, teya-teya commented on tests/06Folders.spec.js
> +        await documentsPage.clickOptionsDropdown();
Если я правильно поняла, что это за выпадающий список то лучше тогда переназвать его как SelectOptionsDropDown

2024-06-21 11:33 UTC, teya-teya commented on tests/03CreateDocument.spec.js
> +        await prepareForSignatureModal.doCanvasClicks();
Светлана у вас не совсем верный тест написан к вашему ТК
в предусловии у вас должна быть уже создана подпись. И тогда шаги теста будут другие и другое модальное окно будет использовано для выбора существующей подписи.

2024-06-21 11:35 UTC, teya-teya requested changes

2024-06-21 11:35 UTC, teya-teya commented on tests/03CreateDocument.spec.js
> +        await createSignatureModal.clickSignNowBtn();
Светлана у вас не совсем верный тест написан к вашему ТК
в предусловии у вас должна быть уже создана подпись. И тогда шаги теста будут другие и другое модальное окно будет использовано для выбора существующей подписи.

2024-06-21 12:41 UTC, SvetlanaKanel commented on tests/06Folders.spec.js
> +        await documentsPage.clickOptionsDropdown();
Мы кликаем по дропдауну, а выбираем из списка

2024-06-21 12:44 UTC, teya-teya commented on tests/06Folders.spec.js
> +        await documentsPage.clickOptionsDropdown();
Но сам дропдаун на странице называется SelectOptions 
Это если я правильно поняла какой элемент используется 
Возможно ошибаюсь

2024-06-22 11:58 UTC, teya-teya commented on tests/06Folders.spec.js
> +        await documentsPage.clickOptionsDropdown();
Тут я спутала, это тесты со старой ПОМ поэтому др, это наверное просто optionDropDown, я просто сначала думала что это элемент на странице documentsPage(он там как раз называется select option) а не tableComponent

2024-07-07 02:07 UTC, closed without merging